version: "3"
services: 
  frontend:
    build:
      context: .
    ports: 
      - "3000:3000"
    env:
      - PRODUCTION=false
  
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3001:3001"
    