name: CI
on: [push]

jobs:
     
  build:
  
    runs-on: ubuntu-latest
     
    steps:
    - name: EC2 deploy
      env:
           KEY: ${{ secrets.EC2_PRIVATE_KEY }}
           ADDRESS: ${{ secrets.EC2_CONNECTION_STRING }}
      run: |
          echo "$KEY" >> private_key.cer;
          chmod 600 private_key.cer;
          BRANCH=${GITHUB_REF/refs\/heads\//}
          CMD="mkdir -p ~/Projects/todo-app-$BRANCH &&
               cd ~/Projects/todo-app-$BRANCH &&
               source ~/.bashrc &&
               git pull origin $BRANCH &&
               nvm use --lts &&
               yarn &&
               yarn build
          "
          ssh -oStrictHostKeyChecking=no -i private_key.cer "$ADDRESS" "bash --login -i -c '$CMD'"
