name: CI
on: [push]

jobs:
     
  build:
  
    runs-on: ubuntu-latest
     
    steps:
    - name: EC2 deploy
      env:
           KEY: ${{ secrets.EC2_PRIVATE_KEY }}
           ADDRESS: ${{ secrets.EC2_CONNECTION_STRING }}
      run: |
          echo "$KEY" >> private_key.cer;
          chmod 600 private_key.cer;
          BRANCH=${GITHUB_REF/refs\/heads\//}
          source ~/.bashrc;
          ssh -oStrictHostKeyChecking=no -i private_key.cer "$ADDRESS" "mkdir -p cd ~/Projects/todo-app-$BRANCH &&
               cd ~/Projects/todo-app-$BRANCH &&
               git pull origin $BRANCH $$
               nvm use --lts &&
               yarn &&
               yarn build
          "
